config/routes.rb
Rails.application.routes.draw do
  resources :racers do
    collection { post :import }
    collection do
      get 'remove_all'
    end
  end

  resources :points do
    collection do
      post :new_multiple
    end
  end

  resources :welcome do
    collection do
      get :route_to_points
    end

    collection do
      get :updated_coords
    end
  end

  resources :races
  resources :routes

  get 'admin/new_race_route'
  get 'admin/admin'

  resources :race_events
  get 'users/new'

  get 'welcome/main'
  get 'welcome/index'

  get 'race_events/index'
  get 'welcome/updated_coords'
  get 'welcome/route_to_points'

  get 'racers/new'
  get 'racers/upload_racers'
  get 'admin/adminlogin'

  root 'welcome#index'
  get 'main' => 'welcome#main'
  get 'index' => 'welcome#index'
  get 'signup' => 'users#new'
  get 'coords' => 'welcome#updated_coords'
  get 'admin' => 'admin#admin'
  get 'adminlogin'=> 'admin#adminlogin'

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  resources :users

end

app/models/racer.rb
class Racer < ActiveRecord::Base
  require 'csv'

  def self.import(file)
    headers   = (CSV.open(file.path, 'r') { |f| f.first }).to_s
    strfname  = headers.match(/\bfirst(\s*name)?/i)[0].strip
    strlname  = headers.match(/\blast(\s*name)?/i)[0].strip
    stremail  = headers.match(/\be-?mail(\s*address)?/i)[0].strip
    strraceid = headers.match(/\b(race(\s*id)?)|(event(\s*id)?)/i)[0].strip
    strbib    = headers.match(/\bbib((\s*id)|(\s*number))?/i)[0].strip
    striscrnt = headers.match(/\bis(\s*current)?/i)[0].strip
    if strfname && strlname && stremail && strraceid && strbib && striscrnt
      CSV.foreach(file.path, headers: true) do |row|
        racer_hash = { :firstname => row[strfname], :lastname => row[strlname], :email => row[stremail], :raceid => row[strraceid], :bib => row[strbib], :iscurrent => row[striscrnt] }
        racer = Racer.where("email = ?", racer_hash[:email])

        if racer.count == 1
          racer.first.update_attributes(racer_hash)
        else
          Racer.create!(racer_hash)
        end

      end # end if headers match
    end # end CSV.foreach
  end # end self.import(file)
end

app/controllers/racers_controller.rb
class RacersController < ApplicationController
  before_action :set_racer, only: [:show, :edit, :update, :destroy]

  # Racer List Upload Function
  def import
    begin
      Racer.import(params[:file])
      redirect_to racers_path, notice: "Racers uploaded successfully!"
    rescue
      redirect_to racers_path, notice: "Invalid CSV file format."
    end
  end

  # GET /racers
  # GET /racers.json
  def index
    @racers = Racer.all
  end

  # GET /racers/1
  # GET /racers/1.json
  def show
  end

  # GET /racers/new
  def new
    @racer = Racer.new
  end

  # GET /racers/1/edit
  def edit
  end

  # POST /racers
  # POST /racers.json
  def create
    newatts = "firstname," + params[:racer][:firstname] + "," +
              "lastname,"  + params[:racer][:lastname]  + "," +
              "email,"     + params[:racer][:email]     + "," +
              "raceid,"    + params[:racer][:raceid]    + "," +
              "bib,"       + params[:racer][:bib]       + "," +
              "iscurrent," + params[:racer][:iscurrent]

    @racer = Racer.new(Hash[*newatts.split(',')])

    respond_to do |format|
      if @racer.save
        format.html { redirect_to @racer, notice: 'Racer was successfully created.' }
        format.json { render :show, status: :created, location: @racer }
      else
        format.html { render :new }
        format.json { render json: @racer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /racers/1
  # PATCH/PUT /racers/1.json
  def update
    respond_to do |format|
      newatts = "firstname," + params[:racer][:firstname] + "," +
                "lastname,"  + params[:racer][:lastname]  + "," +
                "email,"     + params[:racer][:email]     + "," +
                "raceid,"    + params[:racer][:raceid]    + "," +
                "bib,"       + params[:racer][:bib]       + "," +
                "iscurrent," + params[:racer][:iscurrent]

      if @racer.update(Hash[*newatts.split(',')])
        format.html { redirect_to @racer, notice: 'Racer was successfully updated.' }
        format.json { render :show, status: :ok, location: @racer }
      else
        format.html { render :edit }
        format.json { render json: @racer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /racers/1
  # DELETE /racers/1.json
  def destroy
    @racer.destroy
    respond_to do |format|
      format.html { redirect_to racers_url, notice: 'Racer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def indef
    @racers = Racer.all
  end

  def remove_all
    Racer.delete_all
    flash[:notice] = "All racers were successfully removed."
    redirect_to racers_path
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_racer
      @racer = Racer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def racer_params
      #params.require(:racer).permit(:email, :raceid, :bib, :iscurrent)
    end
end

app/helpers/racers_helper.rb
module RacersHelper
end

app/views/racers/_form.html.erb
<style>
  form {
    width: 75%;
    margin: 0 auto;
}
</style>

<%= form_for(@racer) do |f| %>
    <% if @racer.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@racer.errors.count, "error") %> prohibited this racer from being saved:</h2>

          <ul>
            <% @racer.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= f.label :firstname %><br>
      <%= f.text_field :firstname %>
    </div>
    <div class="field">
      <%= f.label :lastname %><br>
      <%= f.text_field :lastname %>
    </div>
    <div class="field">
      <%= f.label :email %><br>
      <%= f.text_field :email %>
    </div>
    <div class="field">
      <%= f.label :raceid %><br>
      <%= f.text_field :raceid %>
    </div>
    <div class="field">
      <%= f.label :bib %><br>
      <%= f.number_field :bib %>
    </div>
    <div class="field">
      <%= f.label :iscurrent %><br>
      <%= f.check_box :iscurrent %>
    </div>
    <div class="actions">
      <%= f.submit "Create/Edit Racer", class: "btn btn-primary" %>
    </div>
<% end %>

app/views/racers/edit.html.erb
<h1><b>Edit Racer</b></h1>

<%= render 'form' %>

<%= link_to 'Show', @racer %> |
<%= link_to 'Back', racers_path %>

app/views/racers/index.html.erb
<%= flash[:notice] %>
<table class='CSSTableGenerator'>
  <thead>
  <tr style='background-color:#b31b1b; color:#ffffff'>
    <th>First Name</th>
    <th>Last Name</th>
    <th>Email</th>
    <th>Race ID</th>
    <th>Bib Number</th>
    <th>Is Current?</th>
  </tr>
  </thead>

  <tbody>
  <% @racers.each do |racer| %>
      <tr>
        <td><%= racer.firstname %></td>
        <td><%= racer.lastname %></td>
        <td><%= racer.email %></td>
        <td><%= racer.raceid %></td>
        <td><%= racer.bib %></td>
        <td><%= racer.iscurrent %></td>
        <td><%= link_to 'Show', racer %></td>
        <td><%= link_to 'Edit', edit_racer_path(racer) %></td>
        <td><%= link_to 'Destroy', { action: :destroy, id: racer.id }, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
  <% end %>
  </tbody>
</table>
<br>
<%= link_to 'Add New Racer', new_racer_path %> |
<%= link_to 'Clear Database', remove_all_racers_path, :method => :get, data: { confirm: 'This will remove all entries from the database. Are you sure?'} %>



<br><br><hr>

<div>
  <h3>Upload Racer List</h3>
  <%= form_tag import_racers_path, multipart: true do %>
      <%= file_field_tag :file %>
      <%= submit_tag "Import CSV" %>
  <% end %>
</div>

<hr>

<button id="helpdivbutton">Is your CSV file not working?</button><br><br>
<script lang="javascript">
  function togglediv() {
    $(".helpdiv").toggle();
  }
  document.getElementById("helpdivbutton").onclick = togglediv;
</script>
<div class="helpdiv" style="display: none">
  <p>CSV files should contain the following columns (extra columns are fine but will not be used):</p>
  <ul>
    <li>First Name</li>
    <li>Last Name</li>
    <li>Email Address</li>
    <li>Race ID</li>
    <li>Bib Number</li>
    <li>Is Current</li>
  </ul>
  <br>
  <p>Any variation of these column names will work (letter case is not important).</p>
  <p>For instance, 'Bib', 'bibNumber', 'Bib Number', 'BibID', and 'bib id' would all work.</p>
  <p>The regular expressions used to match the columns mentioned above are as follows:</p>
  <ul>
    <li>/\bfirst(\s*name)?/i</li>
    <li>/\blast(\s*name)?/i</li>
    <li>/\be-?mail(\s*address)?/i</li>
    <li>/\b(race(\s*id)?)|(event(\s*id)?)/i</li>
    <li>/\bbib((\s*id)|(\s*number))?/i</li>
    <li>/\bis(\s*current)?/i</li>
  </ul>
</div>

app/views/racers/new.html.erb
<%= stylesheet_link_tag "racers" %>
<h1><b>Add A Racer</b></h1>

<%= render 'form' %>

<%= link_to 'Show', @racer %>

app/views/racers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First Name:</strong>
  <%= @racer.firstname %>
</p>

<p>
  <strong>Last Name:</strong>
  <%= @racer.lastname %>
</p>

<p>
  <strong>Email:</strong>
  <%= @racer.email %>
</p>

<p>
  <strong>Race ID:</strong>
  <%= @racer.raceid %>
</p>

<p>
  <strong>Bib Number:</strong>
  <%= @racer.bib %>
</p>

<p>
  <strong>Is Current:</strong>
  <%= @racer.iscurrent %>
</p>

<%= link_to 'Edit', edit_racer_path(@racer) %> |
<%= link_to 'Back', racers_path %>