config/routes.rb
Rails.application.routes.draw do
  resources :racers do
    collection { post :import }
    collection do
      get 'remove_all'
    end
  end

  resources :points do
    collection do
      post :new_multiple
    end
  end

  resources :welcome do
    collection do
      get :route_to_points
    end

    collection do
      get :updated_coords
    end
  end

  resources :races
  resources :routes

  get 'admin/new_race_route'
  get 'admin/admin'

  resources :race_events
  get 'users/new'

  get 'welcome/main'
  get 'welcome/index'

  get 'race_events/index'
  get 'welcome/updated_coords'
  get 'welcome/route_to_points'

  get 'racers/new'
  get 'racers/upload_racers'
  get 'admin/adminlogin'

  root 'welcome#index'
  get 'main' => 'welcome#main'
  get 'index' => 'welcome#index'
  get 'signup' => 'users#new'
  get 'coords' => 'welcome#updated_coords'
  get 'admin' => 'admin#admin'
  get 'adminlogin'=> 'admin#adminlogin'

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  resources :users

end

app/models/race_event.rb
class RaceEvent < ActiveRecord::Base
end

app/controllers/race_events_controller.rb
class RaceEventsController < ApplicationController
  before_action :set_race_event, only: [:show, :edit, :update, :destroy]

  # GET /race_events
  # GET /race_events.json
  def index
    @race_events = RaceEvent.all
  end

  # GET /race_events/1
  # GET /race_events/1.json
  def show
  end

  # GET /race_events/new
  def new
    @race_event = RaceEvent.new
  end

  # GET /race_events/1/edit
  def edit
  end

  # POST /race_events
  # POST /race_events.json
  def create
    @race_event = RaceEvent.new(race_event_params)

    respond_to do |format|
      if @race_event.save
        format.html { redirect_to @race_event, notice: 'Race event was successfully created.' }
        format.json { render :show, status: :created, location: @race_event }
      else
        format.html { render :new }
        format.json { render json: @race_event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /race_events/1
  # PATCH/PUT /race_events/1.json
  def update
    respond_to do |format|
      if @race_event.update(race_event_params)
        format.html { redirect_to @race_event, notice: 'Race event was successfully updated.' }
        format.json { render :show, status: :ok, location: @race_event }
      else
        format.html { render :edit }
        format.json { render json: @race_event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /race_events/1
  # DELETE /race_events/1.json
  def destroy
    @race_event.destroy
    respond_to do |format|
      format.html { redirect_to race_events_url, notice: 'Race event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_race_event
      @race_event = RaceEvent.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def race_event_params
      params.require(:race_event).permit(:raceid, :bib, :time, :latitude, :longitude)
    end
end

app/helpers/race_events_helper.rb
module RaceEventsHelper
end

app/views/race_events/_form.html.erb
<%= form_for(@race_event) do |f| %>
  <% if @race_event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@race_event.errors.count, "error") %> prohibited this race_event from being saved:</h2>

      <ul>
      <% @race_event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :raceid %><br>
    <%= f.text_field :raceid %>
  </div>
  <div class="field">
    <%= f.label :bib %><br>
    <%= f.number_field :bib %>
  </div>
  <div class="field">
    <%= f.label :time %><br>
    <%= f.datetime_select :time %>
  </div>
  <div class="field">
    <%= f.label :latitude %><br>
    <%= f.text_field :latitude %>
  </div>
  <div class="field">
    <%= f.label :longitude %><br>
    <%= f.text_field :longitude %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/race_events/edit.html.erb
<h1>Editing Race Event</h1>

<%= render 'form' %>

<%= link_to 'Show', @race_event %> |
<%= link_to 'Back', race_events_path %>

app/views/race_events/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Race Events</h1>

<table>
  <thead>
    <tr>
      <th>Raceid</th>
      <th>Bib</th>
      <th>Time</th>
      <th>Latitude</th>
      <th>Longitude</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @race_events.each do |race_event| %>
      <tr>
        <td><%= race_event.raceid %></td>
        <td><%= race_event.bib %></td>
        <td><%= race_event.time %></td>
        <td><%= race_event.latitude %></td>
        <td><%= race_event.longitude %></td>
        <td><%= link_to 'Show', race_event %></td>
        <td><%= link_to 'Edit', edit_race_event_path(race_event) %></td>
        <td><%= link_to 'Destroy', race_event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Race event', new_race_event_path %>

app/views/race_events/new.html.erb
<h1>New Race Event</h1>

<%= render 'form' %>

<%= link_to 'Back', race_events_path %>

app/views/race_events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Raceid:</strong>
  <%= @race_event.raceid %>
</p>

<p>
  <strong>Bib:</strong>
  <%= @race_event.bib %>
</p>

<p>
  <strong>Time:</strong>
  <%= @race_event.time %>
</p>

<p>
  <strong>Latitude:</strong>
  <%= @race_event.latitude %>
</p>

<p>
  <strong>Longitude:</strong>
  <%= @race_event.longitude %>
</p>

<%= link_to 'Edit', edit_race_event_path(@race_event) %> |
<%= link_to 'Back', race_events_path %>